/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#10141a',
        'surface': '#10141a',
        'surface-dim': '#10141a',
        'surface-bright': '#353940',
        'surface-container-lowest': '#0a0e14',
        'surface-container-low': '#181c22',
        'surface-container': '#1c2026',
        'surface-container-high': '#262a31',
        'surface-container-highest': '#31353c',
        'surface-variant': '#31353c',
        'on-surface': '#dfe2eb',
        'on-surface-variant': '#bcc9cd',
        'on-background': '#dfe2eb',
        primary: '#96eaff',
        'primary-container': '#4fd1ed',
        'on-primary': '#003640',
        'on-primary-container': '#005766',
        'primary-fixed': '#aaedff',
        'primary-fixed-dim': '#56d6f2',
        secondary: '#a3cdd9',
        'secondary-container': '#224c57',
        'on-secondary': '#03363f',
        'on-secondary-container': '#92bcc8',
        'secondary-fixed': '#bfeaf6',
        'secondary-fixed-dim': '#a3cdd9',
        tertiary: '#ffd6aa',
        'tertiary-container': '#ffb14f',
        'tertiary-fixed': '#ffddb9',
        'tertiary-fixed-dim': '#ffb964',
        'on-tertiary': '#482a00',
        'on-tertiary-container': '#714500',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#869397',
        'outline-variant': '#3d494c',
        'inverse-surface': '#dfe2eb',
        'inverse-on-surface': '#2d3137',
        'inverse-primary': '#006879',
        'surface-tint': '#56d6f2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
